name: recommended_lints
description: Recommended lint rules.
version: 1.0.2
homepage: https://www.leventkantaroglu.com
repository: https://github.com/leventkantaroglu/recommended_lints

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  dart_code_metrics: ^4.15.2